# Generated by Django 5.1.2 on 2024-11-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='Ejemplo', max_length=30)),
                ('baths', models.IntegerField(default='1', max_length=2)),
                ('rooms', models.IntegerField(default='1', max_length=2)),
                ('description', models.CharField(default='Ejemplo0', max_length=100)),
                ('imagen', models.ImageField(blank=True, default='../static/media/casa.webp', upload_to='')),
            ],
        ),
    ]
