# Generated by Django 5.1.2 on 2024-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casas',
            name='contacto',
            field=models.CharField(default='www.whatsapp.com', max_length=100),
        ),
    ]
