# Generated by Django 5.1.2 on 2024-11-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_casas_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casas',
            new_name='Casa',
        ),
    ]
