# Generated by Django 5.1.2 on 2024-12-09 11:57

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=30)),
                ('cuenta', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cuentas_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('tipo_cargo', models.CharField(default='Administrativo', max_length=30)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('passzoho', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuentas_ope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('tipo_cargo', models.CharField(default='Operador', max_length=30)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('passzoho', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='direccionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('nombre_dispositivo', models.CharField(default='Dispositivo no registrado', max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('mac', models.CharField(max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dominios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=50, verbose_name='DOMINION')),
                ('enlace', models.URLField(max_length=60, verbose_name='ENLACE')),
                ('usuario', models.CharField(max_length=30, verbose_name='USUARIO')),
                ('password', models.CharField(max_length=30, verbose_name='PASSWORD')),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('GBYC', 'GBYC'), ('BYCT', 'BYCT'), ('BULL', 'BULL'), ('IVIC', 'IVIC'), ('FEMM', 'FEMM'), ('KCBS', 'KCBS')], default=0, max_length=20)),
                ('responsable', models.CharField(default=0, max_length=20)),
                ('cargo', models.CharField(default=0, max_length=20)),
                ('area', models.CharField(choices=[('Bodega', 'Bodega'), ('Contabilidad', 'Contabilidad'), ('Control y Gestion', 'Gestion y Gestion'), ('Desarrollo', 'Desarrollo'), ('Gerencia', 'Gerencia'), ('Inspector de Equipos', 'Inspector de Equipos'), ('Maquinarias', 'Maquinarias'), ('Operaciones', 'Operaciones'), ('Prevencion de Riesgo', 'Prevencion de Riesgo'), ('Recursos Humanos', 'Recursos Humanos'), ('Relacionadas', 'Relacionadas'), ('Tesoreria', 'Tesoreria'), ('Ventas', 'Ventas')], default=0, max_length=20)),
                ('anydesk', models.IntegerField(blank=True, default=0, max_length=20)),
                ('rustdesk', models.IntegerField(blank=True, default=0, max_length=20)),
                ('password', models.CharField(default=0, max_length=20)),
                ('actaentregado', models.IntegerField(blank=True, default=0, max_length=20)),
                ('fechaentrega', models.DateField(blank=True, null=True)),
                ('actadevolucion', models.IntegerField(blank=True, default=0, max_length=20)),
                ('fechadevolucion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(default=0, max_length=20)),
                ('marca', models.CharField(choices=[('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus')], default=0, max_length=8)),
                ('modelo', models.CharField(default=0, max_length=20)),
                ('nserie', models.CharField(default=0, max_length=20)),
                ('nombre_pc', models.CharField(default=0, max_length=20)),
                ('usuario', models.CharField(default=0, max_length=20)),
                ('marcacpu', models.CharField(default=0, max_length=20)),
                ('modelocpu', models.CharField(default=0, max_length=20)),
                ('ghzcpu', models.CharField(default=0, max_length=20)),
                ('gbram', models.IntegerField(default=0, max_length=2)),
                ('ddrx', models.CharField(default=0, max_length=6)),
                ('mhzram', models.IntegerField(default=0, max_length=4)),
                ('macethernet', models.CharField(default=0, max_length=18)),
                ('macwifi', models.CharField(default=0, max_length=18)),
                ('os', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='nubecorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('departamentos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sesionremota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(choices=[('abod', 'abodByC#887-1'), ('acon', 'aconByC#887-1'), ('adirector', 'adirByC#887-1'), ('amm', 'amaqByC#887-1'), ('apoer', 'aopeByC#887-1'), ('arem', 'aremByC#887-1'), ('arhh', 'arrhByC#887-1'), ('ater', 'atesByC#887-1'), ('aventas', 'avenByC#887-1'), ('bod', 'bodeByC#887-1'), ('cobranza', 'cobrByC#887-1'), ('cont', 'contByC#887-1'), ('ctrl', 'ctrlByC#887-1'), ('fin', 'finaByC#887-1'), ('ger', 'gereByC#887-1'), ('iformat', 'infoByC#887-1'), ('provedores', 'provByC#887-1'), ('reclut', 'reclByC#887-1'), ('relacionadas', 'relaByC#887-1'), ('remu', 'remuByC#887-1'), ('rrhh', 'rrhhByC#887-1'), ('tesor', 'tesoByC#887-1'), ('ventas', 'ventByC#887-1')], max_length=30)),
                ('colaborador', models.CharField(default='DISPONIBLE', max_length=50)),
                ('sistema', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AW', 'AW'), ('CW', 'CW'), ('IW', 'IW'), ('NW', 'NW'), ('OW', 'OW'), ('PW', 'PW'), ('SW', 'SW'), ('EW', 'EW')], max_length=30, null=True)),
                ('certificados', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('JB', 'JB'), ('OW', 'OW')], max_length=30, null=True)),
            ],
        ),
    ]
