# Generated by Django 5.1.2 on 2024-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='numero',
            field=models.IntegerField(max_length=50),
        ),
    ]
