# Generated by Django 5.1.2 on 2024-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_alter_planes_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='company',
            field=models.CharField(choices=[('WOM', 'WOM'), ('ENTEL', 'ENTEL'), ('MOVISTAR', 'MOVISTAR')], max_length=15),
        ),
        migrations.AlterField(
            model_name='planes',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
