# Generated by Django 5.1.2 on 2024-12-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_planes_company_alter_planes_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='status',
            field=models.CharField(choices=[('Asignado', 'Asignado'), ('Dipsonible', 'Disponible')], default='Asignado', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='actadevolucion',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='actaentregado',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='anydesk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='gbram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='mhzram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='rustdesk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='planes',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
