# Generated by Django 3.2.7 on 2024-10-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone number')),
                ('about_me', models.TextField(blank=True, verbose_name='About me')),
                ('license', models.CharField(blank=True, max_length=20, null=True, verbose_name='License')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('is_buyer', models.BooleanField(default=False, help_text='Are you looking to Buy a Property?', verbose_name='Is buyer')),
                ('is_seller', models.BooleanField(default=False, help_text='Are you looking to Sell a Property?', verbose_name='Is seller')),
                ('is_agent', models.BooleanField(default=False, help_text='Are you an Agent?', verbose_name='Is agent')),
                ('top_agent', models.BooleanField(default=False, help_text='Is this Agent a Top Agent?', verbose_name='Top agent')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('num_views', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of views')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
