# Generated by Django 5.1.2 on 2024-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=30)),
                ('cuenta', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cuentas_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('tipo_cargo', models.CharField(default='Administrativo', max_length=30)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('passzoho', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuentas_ope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('tipo_cargo', models.CharField(default='Operador', max_length=30)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('passzoho', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='direccionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('nombre_dispositivo', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('mac', models.CharField(max_length=17, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dominios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=50)),
                ('enlace', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nubecorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('departamentos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sesionremota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('colaborador', models.CharField(max_length=50)),
                ('sistema', models.CharField(max_length=20, null=True)),
                ('certificados', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
