# Generated by Django 5.1.2 on 2024-10-28 15:43

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('GBYC', 'GBYC'), ('BYCT', 'BYCT'), ('BULL', 'BULL'), ('IVIC', 'IVIC'), ('FEMM', 'FEMM'), ('KCBS', 'KCBS')], max_length=20)),
                ('responsable', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='direccionamiento',
            name='nombre_dispositivo',
            field=models.CharField(default='Dispositivo no registrado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dominios',
            name='dominio',
            field=models.CharField(max_length=50, verbose_name='DOMINION'),
        ),
        migrations.AlterField(
            model_name='dominios',
            name='enlace',
            field=models.URLField(max_length=60, verbose_name='ENLACE'),
        ),
        migrations.AlterField(
            model_name='dominios',
            name='password',
            field=models.CharField(max_length=30, verbose_name='PASSWORD'),
        ),
        migrations.AlterField(
            model_name='dominios',
            name='usuario',
            field=models.CharField(max_length=30, verbose_name='USUARIO'),
        ),
        migrations.AlterField(
            model_name='sesionremota',
            name='certificados',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('JB', 'JB'), ('OW', 'OW')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sesionremota',
            name='colaborador',
            field=models.CharField(default='DISPONIBLE', max_length=50),
        ),
        migrations.AlterField(
            model_name='sesionremota',
            name='password',
            field=models.CharField(choices=[('abod', 'abodByC#887-1'), ('acon', 'aconByC#887-1'), ('adirector', 'adirByC#887-1'), ('amm', 'amaqByC#887-1'), ('apoer', 'aopeByC#887-1'), ('arem', 'aremByC#887-1'), ('arhh', 'arrhByC#887-1'), ('ater', 'atesByC#887-1'), ('aventas', 'avenByC#887-1'), ('bod', 'bodeByC#887-1'), ('cobranza', 'cobrByC#887-1'), ('cont', 'contByC#887-1'), ('ctrl', 'ctrlByC#887-1'), ('fin', 'finaByC#887-1'), ('ger', 'gereByC#887-1'), ('iformat', 'infoByC#887-1'), ('provedores', 'provByC#887-1'), ('reclut', 'reclByC#887-1'), ('relacionadas', 'relaByC#887-1'), ('remu', 'remuByC#887-1'), ('rrhh', 'rrhhByC#887-1'), ('tesor', 'tesoByC#887-1'), ('ventas', 'ventByC#887-1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sesionremota',
            name='sistema',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AW', 'AW'), ('CW', 'CW'), ('IW', 'IW'), ('NW', 'NW'), ('OW', 'OW'), ('PW', 'PW'), ('SW', 'SW'), ('EW', 'EW')], max_length=30, null=True),
        ),
    ]
