# Generated by Django 5.1.2 on 2024-10-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_inventario_alter_direccionamiento_nombre_dispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='actadevolucion',
            field=models.IntegerField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='actaentregado',
            field=models.IntegerField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='anydesk',
            field=models.IntegerField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='area',
            field=models.CharField(choices=[('Bodega', 'Bodega'), ('Contabilidad', 'Contabilidad'), ('Control y Gestion', 'Gestion y Gestion'), ('Desarrollo', 'Desarrollo'), ('Gerencia', 'Gerencia'), ('Inspector de Equipos', 'Inspector de Equipos'), ('Maquinarias', 'Maquinarias'), ('Operaciones', 'Operaciones'), ('Prevencion de Riesgo', 'Prevencion de Riesgo'), ('Recursos Humanos', 'Recursos Humanos'), ('Relacionadas', 'Relacionadas'), ('Tesoreria', 'Tesoreria'), ('Ventas', 'Ventas')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='cargo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ddrx',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fechadevolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fechaentrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='gbram',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ghzcpu',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='macethernet',
            field=models.CharField(default=0, max_length=18),
        ),
        migrations.AddField(
            model_name='inventario',
            name='macwifi',
            field=models.CharField(default=0, max_length=18),
        ),
        migrations.AddField(
            model_name='inventario',
            name='marca',
            field=models.CharField(choices=[('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Asus', 'Asus')], default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='inventario',
            name='marcacpu',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='mhzram',
            field=models.IntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='inventario',
            name='modelo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='modelocpu',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombre_pc',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nserie',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='os',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='password',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='rustdesk',
            field=models.IntegerField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='empresa',
            field=models.CharField(choices=[('GBYC', 'GBYC'), ('BYCT', 'BYCT'), ('BULL', 'BULL'), ('IVIC', 'IVIC'), ('FEMM', 'FEMM'), ('KCBS', 'KCBS')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='responsable',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
